version: '3.9'

services:
  app:
    image: markoshust/magento-php:8.1-fpm
    container_name: magento-app
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    environment:
      - MAGENTO_MODE=developer

  web:
    image: nginx:alpine
    container_name: magento-nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: magento-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: magento-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

volumes:
  dbdata:
